node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root@localhost'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:202:8)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at Strategy._verify (C:\Users\IT\Desktop\Justqnodedevelop\src\utils\Authentication\Intranet\UtilPassport.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root@localhost'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root@localhost'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:202:8)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at Strategy._verify (C:\Users\IT\Desktop\Justqnodedevelop\src\utils\Authentication\Intranet\UtilPassport.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root@localhost'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root@localhost'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:202:8)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at Strategy._verify (C:\Users\IT\Desktop\Justqnodedevelop\src\utils\Authentication\Intranet\UtilPassport.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root@localhost'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root@localhost'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:202:8)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at Strategy._verify (C:\Users\IT\Desktop\Justqnodedevelop\src\utils\Authentication\Intranet\UtilPassport.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root@localhost'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root@localhost'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:202:8)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at Strategy._verify (C:\Users\IT\Desktop\Justqnodedevelop\src\utils\Authentication\Intranet\UtilPassport.js:35:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root@localhost'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = 'd1504bc6418f99f0e6e30c134c687e079cb397f31246b7c4fbce56ae'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = 'd1504bc6418f99f0e6e30c134c687e079cb397f31246b7c4fbce56ae'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = 'd1504bc6418f99f0e6e30c134c687e079cb397f31246b7c4fbce56ae'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = 'd1504bc6418f99f0e6e30c134c687e079cb397f31246b7c4fbce56ae'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = 'd1504bc6418f99f0e6e30c134c687e079cb397f31246b7c4fbce56ae'"
}
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19
        controles.sort((a, b) => (a.control_fecha <= b.control_fecha) ? 1 : -1);
                  ^

TypeError: controles.sort is not a function
    at getControles (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Controles\ControllerNavigationControles.js:19:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_BAD_FIELD_ERROR: Unknown column 'envio_reclamacion' in 'field list'
    at Query.Sequence._packetToError (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Pool.query (C:\Users\IT\Desktop\Justqnodedevelop\node_modules\mysql\lib\Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at getReclamaciones (C:\Users\IT\Desktop\Justqnodedevelop\src\controllers\ControllerClientes\Envios\ControllerNavigationEnvio.js:204:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'envio_reclamacion' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT envio_reclamacion FROM envio WHERE envio_id_hash = '3be19bb035665e92f2e6a1b699bce1e32bbef08bb1ec549b90f4266d'"
}
